[server]
headless = true
enableCORS = false
port = 8501
filewatchertype ='poll'

[theme]
base = "light"
primaryColor = "#c73b3b"
backgroundColor = "#000000"
secondaryBackgroundColor = "#5f5b53"
textColor = "#ffffff"
font = "sans serif"